blog/urls.py
#coding:utf8
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('',views.archive,name='blog_list'),
    path('blog-detail/<int:id>/',views.archive_detail,name='blog_detail'),
    path('blog/<int:year>/<int:month>/',views.blog_list_by_date,name='blog_list_by_date'),
    path('blog/categories/<str:category>/',views.blog_list_by_category,name='blog_list_by_category'),
    path('blog/tags/<str:tag>/',views.blog_list_by_tag,name="blog_list_by_tag"),
    path('about/',views.about_me,name='about_me'),
    path('blog/',views.blog_index,name='blog'),
    path('blog-create/',views.create_blog,name='blog_create'),
    #path('blog-delete/<int:id>/',views.delete_blog,name="blog_delete"),
    #path('blog-update/<int:id>/',views.update_blog,name="blog_update"),
]

miroblog/urls.py
from django.contrib import admin
from django.urls import path,include
import blog.urls as blog_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(blog_url,namespace='blog')),
    path('usermanager/',include('usermanager.urls',namespace='usermanager')),
    path('',include('comments.urls',namespace='comments')),
]

usermanager/urls.py
from django.urls import path
from usermanager import views

app_name = 'usermanager'

urlpatterns = [
    path('login/',views.weibo_login,name="login"),
    path('login/process',views.weibo_get_code,name='process'),
    path('logout/',views.user_logout,name='logout')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name
    
class BlogPost(models.Model):
    title = models.CharField(max_length=150)
    body = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    #models.CASCADE的作用是当引用的外键的对象被删除时，本对象也级联删除，django2.0必须传入此参数
    category = models.ForeignKey(Category,default='',on_delete=models.CASCADE)
    #一个标签可以有多篇文章，一篇文章也可能有多个标签，是多对多的关系
    tags = models.ManyToManyField(Tag,default='',blank=True)
    views = models.PositiveIntegerField(default=0)
    class Meta:
        ordering = ('-timestamp',)
    
    #粗略的对文章访问计数，可能存在多个人同时访问不能准确计数的问题
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    def get_absolute_url(self):
        return reverse('blog:blog_detail',args=[self.id])

blog/forms.py
from .models import BlogPost
from django import forms

class BlogPostForm(forms.ModelForm):
    class Meta:
        #指明数据模型来源
        model = BlogPost
        #定义表单包含的字段
        fields = ('title','body')

blog/views.py
from django.shortcuts import render,redirect
from django.template import loader,Context
from django.utils.html import strip_tags
from django.http import HttpResponse
from .models import BlogPost
import markdown
from .forms import BlogPostForm
from django.core.paginator import Paginator
from comments.forms import CommentForm
from comments.models import Comment

# Create your views here.

# 过滤markdown关键字符
def blogs_format(posts):
    md = markdown.Markdown(extensions=['markdown.extensions.extra',
                                       'markdown.extensions.codehilite', ])
    for post in posts:
        safe_post = strip_tags(md.convert(post.body))
        post.body = safe_post
    return posts




#该函数是实现了页面分页，它接收3个参数，依次是用户的request、
#从数据库取得的符合要求的blog以及人为设置的一页可显示的最大文章数目num
def page_button(request,post_list,num):
    paginator = Paginator(post_list,num)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    return posts
 
 # 网站首页视图   
def archive(request):
    posts = blogs_format(BlogPost.objects.all()) # get all blog date from blog database
    
    '''posts_new = []
    for post in posts:
        post.body = markdown.markdown(post.body,
            extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
                ])
        posts_new.append(post)
    context = {'posts':posts_new}
    '''
    context = {'posts':page_button(request,posts,10)}
    return render(request,'blog/index.html',context)


#原理：网页触发请求，指定app内的urls.py的path，再通
#过path，调用views.py内path指定的函数，最后return

# 博客详情视图
def archive_detail(request,id):
    #把posts全部读取后，list2页面实际上已经获得了每
    #一个blogpost的信息，当然也知道每一个blog的id，
    #点击title后，通过urls.py的path的调用指定函数的请求，并
    #传递指定函数的参数（blog的id），函数通过此id重
    #新从数据库获得id对应的blog，并将他显示
    post = BlogPost.objects.get(id = id)
    #post.body= markdown.markdown(post.body,
    #				extensions=[
  	#			  		#常用拓展
 	#			   		'markdown.extensions.extra',
    #					#语法高亮拓展
    #					'markdown.extensions.codehilite',
    #					'markdown.extensions.toc',
    #				])
    md = markdown.Markdown(extensions=[
         'markdown.extensions.extra',
         'markdown.extensions.codehilite',
         'markdown.extensions.toc',
    ])
    
    post.increase_views()
    post.body = md.convert(post.body)
    form = CommentForm()
    #获取这篇post下的全部评论
    comments = Comment.objects.filter(blog=id)
    #动态的给post对象绑定toc属性，不建议这样做
    #更加合理的是直接把toc传给context字典
    #post.toc = md.toc
    context = {'post':post,'toc':md.toc,'comments_list':comments,'form':form}
    return render(request,'blog/detail.html',context)

# 归档处理视图
def blog_list_by_date(request,year,month):
    posts = blogs_format(BlogPost.objects.filter(timestamp__year=year,
                                    timestamp__month=month
                                    ).order_by('-timestamp'))
    #context = {'posts':posts}
    context = {'posts':page_button(request,posts,10)}
    return render(request,'blog/index.html',context)
    
 # 分类处理视图
def blog_list_by_category(request,category):
    posts = blogs_format(BlogPost.objects.filter(category__name=category
                                    ).order_by('-timestamp'))
    #context = {'posts':posts}
    print(posts)
    context = {'posts':page_button(request,posts,10)}
    return render(request,'blog/index.html',context)

def blog_list_by_tag(request,tag):
    print(request)
    print(tag)
    posts = blogs_format(BlogPost.objects.filter(tags__name=tag).order_by('-timestamp'))
    print(posts)
    context = {'posts':page_button(request,posts,10)}
    return render(request,'blog/index.html',context)

# 关于我视图
def about_me(request):
    return render(request,'blog/about.html')

# 博客页面视图
def blog_index(request):
    posts = blogs_format(BlogPost.objects.all())#get all blog date from blog database
    context = {'posts':page_button(request,posts,10)}
    return render(request,'blog/blog.html',context)

def create_blog(request):
    if request.method == "POST":
        #将提交的数据赋值到表单实例中
        blog_post_form = BlogPostForm(data=request.POST)
        #如果提交的内容合法
        if blog_post_form.is_valid():
            #保存数据，不提交
            new_blog = blog_post_form.save(commit=False)
            #保存数据，默认提交
            new_blog.save()
            #跳转网页到blog-list
            return redirect("blog:blog_list")
        else:
            return HttpResponse("表单内容有误，请重新填写")
    #如果用户请求数据（打开创建blog的网页这个动作即为请求）
    else:
        #创建默认的（空的）表单类实例
        blog_post_form = BlogPostForm()
        #赋值上下文
        context = {'blog_post_form':blog_post_form}
        return render(request,'blog/old_version/createblog2.html',context)

'''def delete_blog(request,id):
    #根据id获取需要删除的文章
    blog = BlogPost.objects.get(id=id)
    blog.delete()
    return redirect("blog:blog_list")

def update_blog(request,id):
    #从数据库取得要修改的文章对象
    blog = BlogPost.objects.get(id=id)
    #判断用户是否提交表单数据（已修改完后）
    if request.method == 'POST':
        #创建表单实例对象
        blog_post_form = BlogPostForm(data=request.POST)
        #如果数据合法，将http传递的request直接保存到blog对象中，而没有使用表单对象的数据（虽然是一样的），这样做显然不是很安全，待修改
        if blog_post_form.is_valid():
            blog.title = request.POST['title']
            blog.body = request.POST['body']
            blog.save()
            return redirect('blog:blog_detail',id=id)
        else:
            return HttpResponse("表单存在不合法内容，请修改。")
    else :
        blog_post_form = BlogPostForm()
        context = {'blog':blog,'blog_post_form':blog_post_form,}
        return render(request,'userprofile/update2.html',context)
'''

templates/blog/about.html
{% extends 'blog/base.html' %}
{% block title %}关于|silvers.xyz{% endblock title %}
{% load staticfiles %}
{% block content %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">关于我</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{% static 'blog/img/aboutme.JPG' %}" alt="Developer Image">
								</figure>
								<p>在南昌读书即将要毕业的计科人，正在努力学习计算机相关的知识。目前主要使用python语言开发，会一些html、javascript，现在正在学习Django框架，接下来将继续学习Flask框架。一直想有一个自己的博客平台，学了Django之后，利用所学的知识，搭建了这个博客平台，作为一个学习的巩固。以后我将会不时的在这里面写一些自己对生活，工作和计算机方面的感受和启发，同时也将会继续完善这个博客系统，敬请期待</p>
								
								<p>生活：理性海贼粉、没事喜欢游戏和小说以及知乎</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
								    <li><a href="https://github.com/MrSilvers/" target="_blank">github</a></li>
									<li><a href="https://www.zhihu.com/people/san-du-53/activities" target="_blank">zhihu</a></li>
									<li><a href="https://weibo.com/u/5794633582" target='_blank'>weibo</a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
{% endblock content %}		

templates/blog/base.html
{% load staticfiles %}
{%load blog_tags%}
<html>
<head>
    <title>{% block title %}{% endblock title %}</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <!--<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">-->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!--<link rel="stylesheet" href="{% static 'blog/css/ionicons.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="shortcut icon" href="{% static 'blog/img/H.jpg' %}">
    <!-- js -->
    <!--<script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>-->
    <!--<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>-->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>

<!--顶部-->
{% include 'blog/header.html' %}
<!--中部-->
{% block content %}{% endblock content %}
<!--底部-->
{% include 'blog/footer.html' %}

<!-- Mobile Menu -->
{% include 'blog/mobile.html' %}

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/blog/blog.html
{% extends 'blog/base.html' %}
{% block title %}博客|silvers.xyz{% endblock title %}
{% block content %}
	<div class="content-body">
		<div class="container">
			<div class="row">
				<main class="col-md-12">
				{% for post in posts %}
					<article class="post post-{{ post.id }}">
						<header class="entry-header">
							<h1 class="entry-title">
								<a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a>
							</h1>
							<div class="entry-meta">
								<span class="post-category"><a href="{% url 'blog:blog_list_by_category' post.category.name %}"> {{post.title}} </a></span>

								<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ post.timestamp }}</time></a></span>

								<!--<span class="comments-link"><a href="">4 Comments</a></span>-->
								<span class="views-count"><a>{{post.views}} 阅读</a></span>
							</div>
						</header>
						<div class="entry-content clearfix">
							{{post.body|slice:'100'|safe}}
							<div class="read-more cl-effect-14">
								<a href="{% url 'blog:blog_detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
							</div>
						</div>
					</article>
				{% empty %}
				<div class="no-post">暂时还没有发布的文章！</div>
				{% endfor %}

				<!-- 简单分页效果 -->
				<div class="pagination-simple">
				{% if posts.has_previous %}
				<a href="?page={{ posts.previous_page_number }}">上一页</a>
				{% endif %}
				<span class="current">第 {{ posts.number }} 页 / 共 {{posts.paginator.num_pages}} 页</span>
				{% if posts.has_next %}
				<a href="?page={{ posts.next_page_number }}">下一页</a>
				{% endif %}
			</div>
				</main>
			</div>
		</div>
	</div>
{% endblock content %}		

templates/blog/detail.html
{% extends 'blog/main.html' %}
{% block title %}{{ post.title }}|silvers.xyz{% endblock title %}
{% block blog %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>

            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:blog_list_by_category' post.category.name %}">{{post.category}}</a></span>
                <span class="post-date"><a><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{ post.timestamp }}</time></a></span>

                <!--评论功能暂时不实现-->
                <!--<span class="comments-link"><a>4 评论</a></span>-->

                <span class="views-count"><a>{{post.views}} 阅读</a></span>

            </div>
            <div class="entry-meta">
            {% if post.timestamp != post.updated %}
            <a>文章于<time class="entry-date"
                                   datetime="2012-11-09T23:15:57+00:00">{{ post.updated }}</time>更新</a>
            {% endif %}
            </div>
        </header>
        <hr>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>

    <section class="comment-area" id="comment-area">
        <br>
        <br>
        <br>
        <hr>
        <!--
        {% if request.session.uid %}
        <h3>发表评论</h3>
        <form action="{% url 'comments:comment' post.id %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <label for="{{form.text.id_for_label }}">评论：</label>
                    {{ form.body }}
                    {{ form.body.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
        </form>
        {% else %}
        <br>
        <h4 >
          请<a href="{% url 'usermanager:login' %}" color="#3A5FCD">登录</a>后回复
        </h4>
        <br>
        {% endif %}
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{comment.user.nickname}}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.create_time}}</time>
                    <div class="text">
                        {{comment.body}}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        -->
    </section>
{% endblock blog %}
{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
     {{ toc|safe }}
</div>
{% endblock toc %}

templates/blog/footer.html
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - Powered by<a href="http://www.djangoproject.com/"
                                                        target="_blank" title="Django"> Django</a>
                    - Theme by<a href="http://www.cssmoban.com/" title="cssmoban" target="_blank"> www.cssmoban.com</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/blog/header.html
<!--header-->
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:blog_list' %}"><b>silvers</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:blog_list' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:blog' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about_me' %}" data-hover="关于">关于</a></li>
                            <!--
                            {% if user.is_authenticated %}
                            <li class="cl-effect-11">
                                <a href="#" data-hover="{{ user.nickname }}">
                                {{ user.nickname }}
                                </a>
                            </li>
                            {% else %}
                            <li class="cl-effect-11"><a href="{% url 'usermanager:login' %}" data-hover="登录">登录</a></li>
                            {% endif %}
                            -->
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<!--header-->

templates/blog/index.html
{% extends 'blog/main.html' %}
{% block title %}首页|silvers.xyz{% endblock title%}
{% block blog %}
              {% for post in posts %}
                <article class="post post-{{ post.id }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:blog_list_by_category' post.category.name %}">{{post.category}}</a></span>
                            <span class="post-date"><a><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.timestamp }}</time></a></span>
                            <!--评论功能暂时不实现-->
                            <!--<span class="comments-link"><a>4 评论</a></span>-->
                            
                            <span class="views-count"><a>{{post.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!--<p>{{ post.body|slice:'50'|safe }}...</p>-->
                        {{ post.body|slice:'70'|safe }}
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'blog:blog_detail' post.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                    <hr>
                </article>
              {% empty %}
                <div class="no-post">暂时还没有发布的文章！</div>
              {% endfor %}
                
                <!-- 简单分页效果 -->
                <div class="pagination-simple">
                    {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span class="current">第 {{ posts.number }} 页 / 共 {{posts.paginator.num_pages}} 页</span>
                    {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                
                <!--
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
                -->
{% endblock blog %}            

templates/blog/main.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
            {% block blog %}{% endblock blog %}
            </main>
            <aside class="col-md-4">
              {% block toc %}
              {% endblock toc %}
              {% include 'blog/right.html' %}
            </aside>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/mobile.html
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:blog_list' %}">首页</a></li>
            <li><a href="{% url 'blog:blog_list' %}">博客</a></li>
            <li><a href="{% url 'blog:about_me' %}">关于</a></li>
            <!--
            {% if request.session.uid %}
            <li class="cl-effect-11">
            <a href="{% url 'usermanager:logout' %}" data-hover="{{ request.session.username }}">
            {{request.session.username}}
            </a>
            </li>
            {% else %}
            <li class="cl-effect-11"><a href="{% url 'usermanager:login' %}" data-hover="登录">
            登录
            </a>
            </li>
            {% endif %}
            -->
        </ul>
    </nav>
</div>

templates/blog/right.html
{% load staticfiles %}
{%load blog_tags%}
<div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_list %}
                    <ul>
                        {% for post in recent_list %}
                        <li>
                            <a href="{% url 'blog:blog_detail' post.id %}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:blog_list_by_date' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
                        </li>
                        {% empty %}
                        暂无归档
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:blog_list_by_category' category.name %}">{{ category.name }}
                            <span class="post-count">({{ category.num_posts }})
                            </span>
                            </a>
                        </li>
                        {% empty %}
                        暂无分类
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                      {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:blog_list_by_tag' tag.name %}">{{tag.name}}</a>
                        </li>
                      {% empty %}
                      暂无标签
                      {% endfor %}
                    </ul>
                </div>
                <!--RSS订阅，暂时不实现
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
                -->